abstract class  DoctorScheduleStates{}
class DoctorScheduleInitialState extends DoctorScheduleStates{}

class DoctorSchedulechangeBottomNavBarState extends DoctorScheduleStates{}
class DoctorScheduleCreateDB extends DoctorScheduleStates{}
class DoctorScheduleAddRow extends DoctorScheduleStates{}
class DoctorScheduleChangeBottomState extends DoctorScheduleStates{}