// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCO2rn7MEmvt2u5abRIjrF9tE1Qg_019sg',
    appId: '1:524014311942:android:a289a25669cedd45114187',
    messagingSenderId: '524014311942',
    projectId: 'etma2nproject',
    storageBucket: 'etma2nproject.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVC1hHMbkobEGhKsN2XR_xsed4EOEiKiU',
    appId: '1:524014311942:ios:9c0184ab5c31bb0e114187',
    messagingSenderId: '524014311942',
    projectId: 'etma2nproject',
    storageBucket: 'etma2nproject.appspot.com',
    androidClientId: '524014311942-hsselb27q68ja6u1gd3dmuvjn9faiede.apps.googleusercontent.com',
    iosClientId: '524014311942-q2pu24muav63e114s99fepush9sbhpib.apps.googleusercontent.com',
    iosBundleId: 'com.etma2n.etma2n',
  );
}
